### ISSUE TITLE
Odd support of ✂️ emoji...

### ISSUE THREAD

**Issue by adamjrichman** [playerofgames/logseq-mia-theme#10]
![2022-06-14 at 21 08 33 - Logseq - gm👤✂️  Hanuman](https://user-images.githubusercontent.com/6406117/173734944-f708d5dc-91de-44c8-a5c3-31f8ae7a63e0.jpg)

Scissors showing up properly in one area but not in the other? I did change the font for the titles to be same-same as the rest of the text, but maybe I'm implementing wrong? 

Also btw — this mia-Theme is what got me to use Logseq... I really disliked the default theme and months ago was so turned off I stopped using Logseq, then I found your theme and am now loving it! :)

**Comment by playerofgames** [comment]
I'm not sure what CSS you've used to change the titles, but it may be that another font in the list has the scissors glyph. Using the same font-family as in my comment for #9 should make the presentation consistent.
