### ISSUE TITLE
The container of the page title cannot completely contain the font

### ISSUE THREAD

**Issue by aiirobyte** [playerofgames/logseq-mia-theme#12]
The height of the container is too small when I edit the page title or set bigger font height.
<img width="253" alt="image" src="https://user-images.githubusercontent.com/73283555/209141015-00def31e-7dbe-4cf3-9bf2-cbdbf3fc109e.png">
<img width="205" alt="image" src="https://user-images.githubusercontent.com/73283555/209141092-844c36c4-2834-438d-a9c1-12ce0688c22a.png">

And here is a typo. 
https://github.com/playerofgames/logseq-mia-theme/blob/12ce240b6de81ebbd79a8f924269a00eb2fdf8c5/mia_base.css#L641

**Comment by playerofgames** [comment]
Thanks for reporting. Fixed in release v1.4.7.
