### ISSUE TITLE
Colouring of the bullet threading plugin

### ISSUE THREAD

**Issue by splnkr** [playerofgames/logseq-mia-theme#17]
Hi there,

there is a problem with the colour of the specified path of the bullet threading plugin. The highlighted specified line goes through the highest bullet point. It seems like the bullet point is a tad too low and differs from the other bullets. I use the quattro font.

![CleanShot 2023-05-30 at 03 19 12@2x](https://github.com/playerofgames/logseq-mia-theme/assets/47145749/6e2cfc8e-3110-4b60-93de-c7cdb109c323)

**Comment by playerofgames** [comment]
I don't get the same output you do (thread going beyond the bullet), but the threaded bullet for headings is too high. Do you have other custom css or plugins interacting?

Bullet threading is clever, but makes certain assumptions that aren't valid for all themes. I don't have time to look for a fix right now. If you find a fix that roughly maintains heading spacing, I'd be happy to incorporate it.

**Comment by splnkr** [comment]
I had to reinstall my OS and everything new and somehow the thread going beyond the bullet disappeared. The custom css was not the reason, but maybe some plugin? Right now the plugins I reinstalled do not cause the problem again.  I'll write here again if I get this again and maybe know the cause of this.
