### ISSUE TITLE
scheduled BGcolor under daily page is too dark

### ISSUE THREAD

**Issue by dale502** [playerofgames/logseq-mia-theme#2]
<img width="827" alt="image" src="https://user-images.githubusercontent.com/69394230/160323422-4b00b3be-5ec3-4366-8abe-bb9a888b2ce0.png">
just a suggestion，I think it's too dark

**Comment by playerofgames** [comment]
I agree. There is a 50% opacity applied on that element that reduces contrast too much. I'll release an update shortly.

**Comment by dale502** [comment]
i think these part is not define in dark mode, so they just toally black
other elements have this error 
- query result bgcolor
<img width="788" alt="image" src="https://user-images.githubusercontent.com/69394230/160533390-f807c20a-e9fa-42aa-b39b-9dfb4e864ded.png">
- linked reference bgcolor

**Comment by playerofgames** [comment]
Background colours changed to make things visible and consistent.
