### ISSUE TITLE
How to enable the sidebar help button?

### ISSUE THREAD

**Issue by stephenjen** [playerofgames/logseq-mia-theme#23]
I noticed this theme hides the help button on the sidebar.  Is there a way to enable this button?

**Comment by playerofgames** [comment]
If you mean the "?" help icon in the bottom right corner of the main view, I re-enabled the help button in the 1.6 release (Jan 24). Assuming you are using the most recent release, if the button is hidden for you, then something else is doing it.

If you mean the "Help" heading in the right sidebar, it is not hidden by the theme.
