### ISSUE TITLE
Accidental wrong character in mia_base.css

### ISSUE THREAD

**Issue by abdessalaam** [playerofgames/logseq-mia-theme#24]
In ```mia_base.css``` there is a typo that prevents that element from loading:

in line 112 there is:
```--ls-scrollbar-background-color: r rgba(64,64,64,0.5);```

should be:
```--ls-scrollbar-background-color: rgba(64,64,64,0.5);```

**Comment by playerofgames** [comment]
Thanks, fixed now.
