### ISSUE TITLE
Issue with page embeds and linked references

### ISSUE THREAD

**Issue by sawhney17** [playerofgames/logseq-mia-theme#4]
Love the theme! One of my favorites, especially once you've added the fonts. 
![Screen Shot 2022-04-02 at 7 05 37 PM](https://user-images.githubusercontent.com/80150109/161389348-74747dc7-6b00-4172-a4cd-5761abb8f486.png)
![Screen Shot 2022-04-02 at 7 05 20 PM](https://user-images.githubusercontent.com/80150109/161389351-1311f4f1-7ebc-48ee-bc35-503c849520f7.png)

One quick note, in dark mode, page embeds and linked references are _blindingly white_ hopefully this can be fixed. 

thanks in advance!

**Comment by sawhney17** [comment]
I'm in the duo theme if that's significant and also in the latest nightly of logseq

**Comment by playerofgames** [comment]
This is an incompatibility with the Logseq nightly builds. I'll release a fix.

BTW, what fonts do you have to install? Are you on a Mac?

**Comment by sawhney17** [comment]
Thanks! And yes I'm on a Mac. Why do you ask?

**Comment by playerofgames** [comment]
You said, "especially once you've added the fonts." and I took it to mean that you had to add fonts.

Now I think you _probably_ meant that you liked the Duo font I added to the theme and you did not have to install any fonts.

**Comment by sawhney17** [comment]
Yes that's what I meant. Thanks for the fix!
