### ISSUE TITLE
issue with sidebar color in dark mode and title color

### ISSUE THREAD

**Issue by sawhney17** [playerofgames/logseq-mia-theme#5]
Another thing I've noticed, in dark mode, the sidebar visibility is very low, i think that has to do with changes in the latest nightly of logseq. The title of pages are also in just plain black which makes it impossible to see anything. 

This is in the latest release, was working fine in the past releases
![Screen Shot 2022-04-02 at 7 08 37 PM](https://user-images.githubusercontent.com/80150109/161389463-c1fb7729-7228-494b-9cf3-287ad38a4751.png)
![Screen Shot 2022-04-02 at 7 11 30 PM](https://user-images.githubusercontent.com/80150109/161389586-46cbc298-7781-4cfd-9fea-5051e921b4ab.png)

**Comment by playerofgames** [comment]
This is an incompatibility with the Logseq nightly builds. I'll release a fix.
