### ISSUE TITLE
Logseq Markmap discrepancy

### ISSUE THREAD

**Issue by crendl** [playerofgames/logseq-mia-theme#7]
Hi,

For some reason, the miA theme is not compatible with the Logseq Markmap (v0.2.1) plugin.
The heading container (?) of a page seems to cover the plugin.

![image](https://user-images.githubusercontent.com/15796851/165539537-90fd9893-a681-4d03-94f0-6b66e6798612.png)
![image](https://user-images.githubusercontent.com/15796851/165539693-0fd3e40c-1c59-42db-a3b4-c88600bc3298.png)

**Comment by playerofgames** [comment]
This was a personal preference that was left in when I released the theme publicly. I've fixed this in v1.1.4.

**Comment by crendl** [comment]
appreciated, thanks!
