### ISSUE TITLE
No ❌ emoji support

### ISSUE THREAD

**Issue by adamjrichman** [playerofgames/logseq-mia-theme#9]
The theme is not correctly rendering the ❌ emoji or the !! or the ⁉️ — I've tried switching the default font to IBM Plex Mono (which works elsewhere, with Workflowy, and other areas of macOS) to no avail. Neither the iA Writer Mono font or IBM Plex will render the emoji correctly. 
![2022-06-09 at 15 46 18 - Logseq - Font Check  Hanuman](https://user-images.githubusercontent.com/6406117/172931919-0394295b-42df-4fe3-a3ce-827ae59ea089.jpg)

**Comment by playerofgames** [comment]
As far as I can tell, if the font provides a unicode implementation of the emoji unicode, this will win over the system emoji font. IBM Plex provides a glyph for ❌, but not for ⁉️ . However, the next font in the list is 'sans-serif' which implements interrobang.

If you add
```
.ls-card,	
.sidebar-item .content,
#main-content-container .content {
	font-family: var(--content-font-family), "Apple Color Emoji", "Segoe UI Emoji";
}
```

to `custom.css` then at least you'll get the interrobang. I'll update the theme with this change shortly.

**Comment by adamjrichman** [comment]
Appreciate the response! Take a look at this crude example here where I've dropped your example at the top... I can actually get the ❌ to show up properly just by including 'monospace' — when I include Apple Color Emoji, I do get the interrobang... but it's weird... it's not like it's "building" on top of IBM Plex Mono (or iA Writer) like it should be... by contrast, in Workflowy I also run custom CSS and the only bit Workflowy needs is the IBM Plex Mono and monospace combination to properly render the ❌. Experimenting with a conversion from WF to Logseq, and it's literally held up by this one character that I use everywhere, ha. I appreciate the help and peeking into this my friend! 🙌 

https://user-images.githubusercontent.com/6406117/173991519-71d5ea01-8011-41ec-a720-eb548b0f6eab.mp4

**Comment by playerofgames** [comment]
I dug deeper into what was going on, and found a fix—using `unicode-range` on the `@font-face` declarations.

**Comment by adamjrichman** [comment]
Huzzah! Fabulous, thank you!!
